version: '3.3'

services:
  springboot:
    image: dockerdreamz25/spring-boot-mongo:latest
    environment:
    - MONGO_DB_HOSTNAME=mongo
    ports:
      - 9090:8080
    networks:
    - springappnetwork  
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    networks:
    - springappnetwork
volumes:
  mongodb:
networks:
  springappnetwork:
   
