version: '3.8'

services:
  springboot:
    image: dockerdreamz25/spring-boot-mongo:$buildNumber
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 9090:8080
    networks:
    - springappnetwork  
    

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    
    
networks:
  springappnetwork:
   
